language: go

go:
  - "1.14.x"
sudo: required

services:
- docker

stages:
- test
- build

jobs:
  include:
  - stage: test
    script:
    - make test
    after_success:
    - make coverage
  - stage: build
    if: tag IS present
    env:
    - secure: cGWzCN3cNv9kP7ibRlL90bUWAUHXK4qNRO0k71k35NoS+dWCpGxH2BVxAlGcIUao4VCiH/POhA69+A//bINC24cDAJMyEi+zS+q/HvxqnGpGIS1prJyR+5gZhiEs0KThBmkAKQghDAuLFIZtMQSVqlG4LGoDKWK7cCZ0i+kOnJWWyZ1knOLwyOxZtknL/cR4eaYHy6czObSnoWWV6sRL+d9DkDrssDhv3oQfERITPGjlWqIuVCvvIbd/TQxwjG2KUuEwruJpVZMsReyjZ6qkVZV8sH6RuRiYfGaVmvfiuQECiiTkL7MdsnKUWnRxHcd/zkVjeGnZsVtTk9icq/1gkKQgurQSYbMuxaS/LPM+Tj97UOhQQH8/KXJn/880lDAqn+3Jlx6ZZ5nT7XykszW3N5Qu8cz8qp5Tx2/lXIaIfiDNLXm8SdfYfeD7rJQj2McPn6lPvF8G4y14NQLiNxGzCivF2iiSC+BeqkwEYiU/ML7v5jxPoVjrCcDG3r0YbJbuvtgm/BP+tLU6xpgoSsfbce8T1J0NA3HzvJNRqi+7TyOyDMK6Le5dXXDd/F0Wm8PP93paZl7QszNTIcF0ncBCRc4EriZT2TrzGBR/2s31js2ICJAxJ0bfMLZ+CYOFsWkaM6z4OQ4OzN5VbNIN+IzpICX+pMkDB7MpQXAgRXFXjqU=
    - secure: kGo33sW+1OLDC1DXlgA/jSHeh+m4DT7DRKKqc1reoQ7cvXt8MBVadZsxki4In+jIkyrRoecGE0dW2XorXifD+uDslNrY4uvU+kFKr2G3hi7AilIrrjNgtW5mj4QVZuNk8ORu2leLSmWx/L4PcMtRReJGhjyrvt7nfgtn7kaF74Or+nAg50SbZ/iNojouqJ2+a4zYQtD4KMuqbMhOd5KGOXRwYrfeH7Ue8OptmzMdEodvxFAc06jt0sVJXzz0SRaWg6i/BmQORTH3T5P6E1ODeh6pkH/DXPi17iUUk7DEqWUfhQbhSb4By726eM57juIZCG01yCdVmDQgZ7V5ZFGMJLP7PB4PzAt17awJFxN0EPNnuZ8NhlY1XWNBBFB3Bj+ExIVry6c4cpggxrU5Xft5tspa+c2TMiydjSLrKnwUK1EVBei0GWxZKVmjKKv/Xv71P3NN6J9LzybaPaHoYZUNit2XnvItTseS3grfwwAa1NS6XE2jkTQppSM8vKj6Ikzu0V8AQkHkR2LATJUWuJu9ILgw5uXfWbUfKjFJAKKiw7W3+Hs7IuqxcRxwDXiRxpwYlErDk7/G33gujhOvn9evgNzxf2pVcgyU0H7qo6iWZduTtzFJsGwfBqHlURv8D/p1HtCZEFtc2aZjpm33I3Z0oTo+lUM5OyAvU3WpBl0Ht8k=
    script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - make DOCKER_TAG=$TRAVIS_TAG docker-build
    - make docker-build
    - make DOCKER_TAG=$TRAVIS_TAG docker-push
    - make docker-push

env:
  global:
    secure: L5EXD8R2wR2kURGcO1Mqfp2Vct9SlJVuPrBFkYWC9aFGA6Y3+X85nIe3mlzfal+IqEFjjaJysCAPmBF+DVZl96/5fJCwSEtsp5pBv4OmRa3OvXbL8iMK9lGE/SQuitR3YnJzbWmvZ+EO37NXsTogaH2iYlB6NcUi9VCVz8YW/w3Nbqisb2RkM1e6kWHkRXxtbUWiTOMY5iozkGm/rMUBwlpcSa41C5JwEZqrgbC2dsdv7u81haCVfEz4lijT24bplnkXesxiV2khu3Nl0bR58CY2p28kuhz+HXBsnIRcyvX1JU3yERIYWdF6sxW5uPzFIqDKrFw3VxGP33BqUL0ZAQogUWYzrwBiZqwYh3awdahmkuGeeP7zrcM22vVQSwohc7P+A+9DLZsyxiP7haTJ05EY8yU+H7fQlTamq77LBdrFglIBWgMuHpkGkkoZhciKfiKKwBifhC42QOnAz/7+JCHYCzimo0peOYMQcKQOZfnVvXoA9KLPAylGCHOyO7C3SUMPVVBueY7iwb8vr1+a1Pgj5/JHeJ/avzpTjSZBWEqWNOpXxiF29ZxPnSus+vTWHMkUBKjQOELNUrp0lsMKSqucIcjcDiko40YhgYAAORn2Yrn43byHvXINiacsQB7sg+jj2sOaY63bnsAzKpsytJnXzPw9iGCZHA9dMA/sOIk=
