language: go
go:
  - 1.14.x
sudo: required
services:
  - docker
stages:
  - test
  - build
jobs:
  include:
    - stage: test
      name: run tests
      script:
        - make kind-create
        - make test
      after_success:
        - make coverage
    - stage: test
      name: lint code
      script:
        - make lint
    - stage: build
      name: release docker images
      if: branch = master AND tag IS present AND type != pull_request
      env:
        - secure: cGWzCN3cNv9kP7ibRlL90bUWAUHXK4qNRO0k71k35NoS+dWCpGxH2BVxAlGcIUao4VCiH/POhA69+A//bINC24cDAJMyEi+zS+q/HvxqnGpGIS1prJyR+5gZhiEs0KThBmkAKQghDAuLFIZtMQSVqlG4LGoDKWK7cCZ0i+kOnJWWyZ1knOLwyOxZtknL/cR4eaYHy6czObSnoWWV6sRL+d9DkDrssDhv3oQfERITPGjlWqIuVCvvIbd/TQxwjG2KUuEwruJpVZMsReyjZ6qkVZV8sH6RuRiYfGaVmvfiuQECiiTkL7MdsnKUWnRxHcd/zkVjeGnZsVtTk9icq/1gkKQgurQSYbMuxaS/LPM+Tj97UOhQQH8/KXJn/880lDAqn+3Jlx6ZZ5nT7XykszW3N5Qu8cz8qp5Tx2/lXIaIfiDNLXm8SdfYfeD7rJQj2McPn6lPvF8G4y14NQLiNxGzCivF2iiSC+BeqkwEYiU/ML7v5jxPoVjrCcDG3r0YbJbuvtgm/BP+tLU6xpgoSsfbce8T1J0NA3HzvJNRqi+7TyOyDMK6Le5dXXDd/F0Wm8PP93paZl7QszNTIcF0ncBCRc4EriZT2TrzGBR/2s31js2ICJAxJ0bfMLZ+CYOFsWkaM6z4OQ4OzN5VbNIN+IzpICX+pMkDB7MpQXAgRXFXjqU=
        - secure: PXCgo+r5Tzb6swDz8OLXVkrUInQouc9MBSSVRsMQVmCLSomzNYUy2U/D4Ue3Udc6LhVXMMXSgwua5SLpqYlYpP2u6zIe9LkxHnVwzbR/TVm1VqFa11wr0/K5CLdz5b1EDAM3R/MMEo7/6oAcnOj1SsI804a9rJfg+8cDCY7lv/jHt3ufBEE4wlwlDql+9J79iCGj94WlpMpgaAaXQsHuLcwS5SDUJury6WhxFkVp3yxc+iAXe7iS4tCfybda0g1HfwqwGNwsbTo6WFKK5QSPgrufu2xsjxGJwU324cV5a1DW0MUkcfwwjPy2yYwK2PIGwWXHrgjCcs5A979FgeahxqRRyCY4A27eK/QigmIYAv9qtDLYBGS8blqJU3n0U2JK2P1B8zJyXr3REy3j8nP6ydyhbpNze3JYnh/iJW2BXMgz1f4YF8BEwXDx5WpyfcNj5qf5N7vJryJzXXh5JlUpIC99Cm4NMnWeiNX4mi+OeJQ7nFQHI1KBCFrQ/Y7y64/xh3HhjpJ0YkaiNWw7oUxG+lmw/4KZ2scNxW0hg7ShuMbdJvbmoyZhpUc1LkeJjwRRmqHH/PC30V/2dviwwxrIOVy4OsHIHJ7ftG7khv9snLgYpKNETmMhkMePyOt/KeN9jG6366prM6+BM1E4ERi+ZuDXoqL2eD66jbRh6vzDiDw=
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - make DOCKER_TAG=$TRAVIS_TAG docker-build
        - make docker-build
        - make DOCKER_TAG=$TRAVIS_TAG docker-push
        - make docker-push
    - stage: publish
      if: branch = master AND tag IS present AND type != pull_request
      install:
        - curl https://raw.githubusercontent.com/kubernetes/helm/master/scripts/get | bash
        - helm init --client-only
      script:
        - helm lint charts/backup-operator
        - ./ci/travis-docker-fix
        - ./ci/publish
env:
  global:
    secure: L5EXD8R2wR2kURGcO1Mqfp2Vct9SlJVuPrBFkYWC9aFGA6Y3+X85nIe3mlzfal+IqEFjjaJysCAPmBF+DVZl96/5fJCwSEtsp5pBv4OmRa3OvXbL8iMK9lGE/SQuitR3YnJzbWmvZ+EO37NXsTogaH2iYlB6NcUi9VCVz8YW/w3Nbqisb2RkM1e6kWHkRXxtbUWiTOMY5iozkGm/rMUBwlpcSa41C5JwEZqrgbC2dsdv7u81haCVfEz4lijT24bplnkXesxiV2khu3Nl0bR58CY2p28kuhz+HXBsnIRcyvX1JU3yERIYWdF6sxW5uPzFIqDKrFw3VxGP33BqUL0ZAQogUWYzrwBiZqwYh3awdahmkuGeeP7zrcM22vVQSwohc7P+A+9DLZsyxiP7haTJ05EY8yU+H7fQlTamq77LBdrFglIBWgMuHpkGkkoZhciKfiKKwBifhC42QOnAz/7+JCHYCzimo0peOYMQcKQOZfnVvXoA9KLPAylGCHOyO7C3SUMPVVBueY7iwb8vr1+a1Pgj5/JHeJ/avzpTjSZBWEqWNOpXxiF29ZxPnSus+vTWHMkUBKjQOELNUrp0lsMKSqucIcjcDiko40YhgYAAORn2Yrn43byHvXINiacsQB7sg+jj2sOaY63bnsAzKpsytJnXzPw9iGCZHA9dMA/sOIk=
before_install:
  -
