# permissions for end users to view consulbackupplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consulbackupplan-viewer-role
rules:
- apiGroups:
  - backup.kubism.io
  resources:
  - consulbackupplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.kubism.io
  resources:
  - consulbackupplans/status
  verbs:
  - get
