# permissions for end users to view mongodbbackupplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbbackupplan-viewer-role
rules:
- apiGroups:
  - backup.finleap.cloud
  resources:
  - mongodbbackupplans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - backup.finleap.cloud
  resources:
  - mongodbbackupplans/status
  verbs:
  - get
