# permissions for end users to edit mongodbbackupplans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongodbbackupplan-editor-role
rules:
- apiGroups:
  - backup.finleap.cloud
  resources:
  - mongodbbackupplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.finleap.cloud
  resources:
  - mongodbbackupplans/status
  verbs:
  - get
