apiVersion: backup.finleap.cloud/v1alpha1
kind: ConsulBackupPlan
metadata:
  name: consulbackupplan-sample
spec:
  schedule: "0 22 * * *"
  activeDeadlineSeconds: 3600
  retention: 3
  address: "localhost:8500"
  username: $CONSUL_HTTP_USERNAME
  password: $CONSUL_HTTP_PASSWORD
  destination:
    s3:
      endpoint: "localhost:8000"
      bucket: "test"
      useSSL: true
      accessKeyID: $S3_ACCESS_KEY_ID
      secretAccessKey: $S3_SECRET_ACCESS_KEY
      encryptionKey: $S3_ENCRYPTION_KEY
  env:
    - name: CONSUL_HTTP_USERNAME
      value: "user"
    - name: CONSUL_HTTP_PASSWORD
      valueFrom:
        secretKeyRef:
          key: consul-password
          name: my-consul-credentials
    - name: S3_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: my-s3-credentials
          key: S3_ACCESS_KEY_ID
    - name: S3_SECRET_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: my-s3-credentials
          key: S3_SECRET_ACCESS_KEY
    - name: S3_ENCRYPTION_KEY
      valueFrom:
        secretKeyRef:
          name: my-s3-credentials
          key: S3_ENCRYPTION_KEY
