apiVersion: backup.kubism.io/v1alpha1
kind: ConsulBackupPlan
metadata:
  name: consulbackupplan-sample
spec:
  schedule: "* * * * *"
  activeDeadlineSeconds: 3600
  retention: 2
  uri: "localhost:8500"
  destination:
    s3:
      endpoint: "localhost:8000"
      bucket: "test"
      useSSL: true
  env:
    - name: CONSUL_HTTP_USERNAME
      value: "user"
    - name: CONSUL_HTTP_PASSWORD
      value: "password"
    - name: S3_ACCESS_KEY_ID
      value: "abc"
    - name: S3_SECRET_ACCESS_KEY
      value: "abc"
    - name: S3_ENCRYPTION_KEY
      value: "256bit"
