namespace: "{{ .Release.Namespace }}"
namePrefix: "{{ .Release.Name }}-backup-operator-"

bases:
- ../rbac

patchesStrategicMerge:
# Patching ServiceAccount
- patches/leader_election_role_binding_patch.yaml
- patches/role_binding_patch.yaml
