namespace: "{{ .Release.Namespace }}"
namePrefix: "{{ .Release.Name }}-backup-operator-"

bases:
- ../rbac

patchesStrategicMerge:
# Patching ServiceAccount
- leader_election_role_binding_patch.yaml
- role_binding_patch.yaml