namespace: "{{ .Release.Namespace }}"
namePrefix: '{{ include "backup-operator.fullname" . }}-'

bases:
- ../rbac

patchesStrategicMerge:
# Patching ServiceAccount
- patches/leader_election_role_binding_patch.yaml
- patches/role_binding_patch.yaml
