---
{{- if .Values.useOldCertManager }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
{{- if .Values.useOldCertManager }}
apiVersion: certmanager.k8s.io/v1alpha1
{{- else }}
apiVersion: cert-manager.io/v1alpha2
{{- end }}
kind: Certificate
metadata:
  name: {{ .Values.name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
{{- if .Values.useOldCertManager }}
  commonName: {{ .Values.name }}-webhook-service.{{ .Release.Namespace }}.svc
{{- end }}
  dnsNames:
  - {{ .Values.name }}-webhook-service.{{ .Release.Namespace }}.svc
  - {{ .Values.name }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ .Values.name }}-cert
