apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    app: {{ .Values.name }}
  name: {{ .Values.name }}-controller-manager
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: controller-manager
        app: {{ .Values.name }}
    spec:
      serviceAccountName: backup-operator
      containers:
      - args:
        - --enable-leader-election
        command:
        - /manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: manager
        ports:
        - containerPort: 443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      terminationGracePeriodSeconds: 10