{{ $name := (printf "%s-backup-operator" .Release.Name) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
    app: {{ $name }}
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      control-plane: controller-manager
      app: {{ $name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        control-plane: controller-manager
        app: {{ $name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-backup-operator
      containers:
      - args:
        - --enable-leader-election
        - --worker-image={{ .Values.image.repository }}:{{ .Values.image.tag }}
        command:
        - /manager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: manager
        ports:
        - containerPort: 443
          name: webhook-server
          protocol: TCP
        - containerPort: 8080
          name: metrics
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      terminationGracePeriodSeconds: 10
