apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "backup-operator.fullname" . }}-leaderelection
  labels:
    {{- include "backup-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "backup-operator.fullname" . }}-leaderelection
  labels:
    {{- include "backup-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "backup-operator.fullname" . }}-leaderelection
subjects:
- kind: ServiceAccount
  name: {{ include "backup-operator.serviceAccountName" . }}
  namespace: "{{ .Release.Namespace }}"
