---
apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ .Values.name }}-metrics
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    control-plane: controller-manager
    app: {{ .Values.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-webhook-service
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    control-plane: controller-manager
    app: {{ .Values.name }}
