#!/usr/bin/env bash
set -euo pipefail

wd=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
tmp_dir=$(mktemp -d)
function cleanup {
    rm -rf $tmp_dir
}
trap cleanup EXIT
curl -L https://get.helm.sh/helm-v3.1.2-$(go env GOOS)-$(go env GOARCH).tar.gz | tar -xz -C ${tmp_dir}
mv ${tmp_dir}/$(go env GOOS)-$(go env GOARCH)/helm ${wd}/helm3
