#!/usr/bin/env bash
set -euo pipefail

wd=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
tmp_dir=$(mktemp -d)
function cleanup {
    rm -rf $tmp_dir
}
trap cleanup EXIT
curl -L https://go.kubebuilder.io/dl/2.3.1/$(go env GOOS)/$(go env GOARCH) | tar -xz -C ${tmp_dir}
find ${tmp_dir}/kubebuilder_2.3.1_$(go env GOOS)_$(go env GOARCH) -type f -print0 | xargs -0 mv -t ${wd}
