#!/usr/bin/env bash

set -euo pipefail
wd=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

if [[ ! -f ${wd}/kubebuilder ]]; then
  echo "Please run 'make tools' first to install prerequisites"
  exit 1
fi

function setup_kubebuilder_scaffolding {
  mv ${wd}/../pkg/controllers ${wd}/../controllers
  mv ${wd}/../cmd/manager/main.go ${wd}/../main.go
}

function restore_project_scaffolding {
  mv ${wd}/../controllers ${wd}/../pkg/controllers
  mv ${wd}/../main.go ${wd}/../cmd/manager/main.go
}

setup_kubebuilder_scaffolding
trap restore_project_scaffolding EXIT

${wd}/kubebuilder $@ --make=false

