#!/usr/bin/env bash

set -euo pipefail
wd=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)

os=$(go env GOOS)
arch=$(go env GOARCH)
version=2.3.1

dir="${wd}/kubebuilder_${version}_${os}_${arch}"

if [[ ! -d "${dir}" ]]; then
  curl -L https://go.kubebuilder.io/dl/${version}/${os}/${arch} | tar -xz -C ${wd}
fi

function setup_kubebuilder_scaffolding {
  mv ${wd}/../pkg/controllers ${wd}/../controllers
  mv ${wd}/../cmd/manager/main.go ${wd}/../main.go
}

function restore_project_scaffolding {
  mv ${wd}/../controllers ${wd}/../pkg/controllers
  mv ${wd}/../main.go ${wd}/../cmd/manager/main.go
}

setup_kubebuilder_scaffolding
trap restore_project_scaffolding EXIT

${dir}/bin/kubebuilder $@ --make=false

