apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leader-election-rolebinding
subjects:
- kind: ServiceAccount
  name: "{{ .Release.Name }}-backup-operator"
  namespace: "{{ .Release.Namespace }}"
