name: Draft Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
      
jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - name: Update draft
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}